### ISSUE TITLE
Error about "blocked by CORS policy"

### ISSUE THREAD

**Issue by Lier007** [hua1995116/google-translate-open-api#1]
Access to XMLHttpRequest at 'https://translate.google.cn/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by hua1995116** [comment]
It only supports Node.js or chrome extensions, If you want to use it in browsers, maybe you should need a proxy.

**Comment by Lier007** [comment]
Sorry，I'm a rookie in terms of js. It reports this error when running with node.js.

(function (exports, require, module, __filename, __dirname) { import translate from 'google-translate-open-api';

**Comment by hua1995116** [comment]
From your error, it looks you want to request 'google.cn' from your origin 'http://localhost:8080'. It seems not in Node.js. Are you use it in your  React/ Vue project? Not Node.js?

**Comment by hua1995116** [comment]
If your want to use it on browers. you can use [cors-anywhere](https://github.com/Rob--W/cors-anywhere/).   
[Live Demo](http://cors-anywhere.herokuapp.com)

**Comment by Lier007** [comment]
The first is on browser. the second error is running in Node.js. The scene is like this:

~/code/translate$ node openapi.js 
/home/yons/code/translate/openapi.js:1
(function (exports, require, module, __filename, __dirname) { import translate from 'google-translate-open-api';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by hua1995116** [comment]
This is no problem with  **google-translate-open-api**.
Because Node.js is not native support import. You can use the following code.
```
const translate = require('google-translate-open-api').default;
(async() => {
  const result = await translate(`I'm fine.`, {
    tld: "cn",
    to: "zh-CN",
  });
  const data = result.data[0];
  console.log(data);
})()
```

**Comment by Lier007** [comment]
Wow, it's OK! 
But the “Multi-segment text contains multi-sentence.” mode is right for me. Can you provide one such version? 
And in this mode, Can I pass in 10,000 sentences at a time?

**Comment by hua1995116** [comment]
https://github.com/hua1995116/google-translate-open-api#usage

case 3

**Comment by Lier007** [comment]
When I run in case 3 directly: It reports the same error like this:
(function (exports, require, module, __filename, __dirname) { import translate, { parseMultiple } from 'google-translate-open-api';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

When I modified it like this:
const translate = require('google-translate-open-api').default;
(async() => {
  const result = await translate([`I'm fine. And you?`,`I'm ok.`], {
    tld: "cn",
    to: "zh-CN",
  });
  const data = result.data[0];
  console.log(data);
})()

The result is:
[ [ [ [Array] ], null, 'en' ], [ [ [Array] ], null, 'en' ] ]

**Comment by hua1995116** [comment]
yeah, this is ok.
```
console.log(JSON.stringify(data));
```
you can see the hidden result.

**Comment by Lier007** [comment]
Yeah, I get middle result like this.
 """ [[[["<i>I&#39;m fine.</i> <b>我很好。</b> <i>And you?</i> <b>你呢？</b>"]],null,"en"],[[["我可以。"]],null,"en"]] """

How can I use function similar with "parseMultiple" to get the final result 
 ["我很好。你呢？","我可以。"]

**Comment by hua1995116** [comment]
Use function `parseMultiple`, the `parseData` is you wanted.
```
// use parseMultiple
const data = result.data[0];
const parseData = parseMultiple(data);
// ["我很好。你呢？","我可以。"]
```
This is all in README.md.

**Comment by Lier007** [comment]
Yes, but I haven't  "import translate, { parseMultiple } from 'google-translate-open-api';". 
So I can can't use "parseMultiple" directly.
(node:14956) UnhandledPromiseRejectionWarning: ReferenceError: parseMultiple is not defined

**Comment by hua1995116** [comment]
const parseMultiple = require('google-translate-open-api'). parseMultiple;

**Comment by Lier007** [comment]
Thank you very very much!!!
