### ISSUE TITLE
403 - Your client does not have permission to get URL

### ISSUE THREAD

**Issue by Paul-creator** [hua1995116/google-translate-open-api#10]
After hundrets of requests this error occured.

**Comment by hua1995116** [comment]
It may be that Google limits the frequency of such requests for ip detection

**Comment by Paul-creator** [comment]
But i get the same error when using a vpn

**Comment by hua1995116** [comment]
Due to the stateless nature of http, I do n’t think it will record your history, I think it may be limiting your concurrent volume at the same time. Can it be changed to a smaller amount of requests at the same time?

**Comment by Paul-creator** [comment]
I make only one request at a time.

**Comment by Paul-creator** [comment]
It turned out that I had some funny characters in the text I wanted to translate.

**Comment by hua1995116** [comment]
For example ? I also want to know the reason for your problem

**Comment by Paul-creator** [comment]
I had a txt file which looked like that when i opened it with the TextEdit of my mac:
Some text

when i opened it in Javascript with:
```
function readTextFile(file, callback)
{
    var rawFile = new XMLHttpRequest();
    rawFile.open("GET", file, false);
    rawFile.onreadystatechange = function ()
    {
        if(rawFile.readyState === 4)
        {
            if(rawFile.status === 200 || rawFile.status == 0)
            {
                var allText = rawFile.responseText;
                callback(allText)
            }
        }
    }
    rawFile.send(null);
}
```
it looked like that:
�� Some text

To get rid of the �� I had to create a new txt file and write the text manually in it. 
After removing � everything worked.

But now when i translate somthing with � in it, it works. Maybe there were some more invisible characters.

**Comment by Paul-creator** [comment]
[en.txt](https://github.com/hua1995116/google-translate-open-api/files/4554485/en.txt)
(I found the file on another computer.)
Opening it with the js function is the only knowen way to see the �

**Comment by hua1995116** [comment]
You can use this code to filter invisible characters
https://gist.github.com/hachesilva/87cbd2b499e08d66a6acac16bc17d373

**Comment by Paul-creator** [comment]
It crashes in line: ` this.code.set(content);` (Also I don't understand what this line means.)
I tried `content = content.split('�').join('')` and when i logged the content, the � where gone, but i couldn't translate the content, even without the � - I still got the 403 error.

**Comment by hua1995116** [comment]
Have you tried it in [Google Translate](https://translate.google.com)?

**Comment by Paul-creator** [comment]
<img width="707" alt="Screenshot 2020-04-30 at 2 24 11 PM" src="https://user-images.githubusercontent.com/52125859/80709884-6637bd80-8aee-11ea-9ffe-22b439aa6d64.png">
It works.
It seems like there are other invisible characters in this file, which is why it doesn't work in the javascript project. (This file was crated on Windows by someone who doesn't know how he encoded it.)
