### ISSUE TITLE
JSdom environment causes problems

### ISSUE THREAD

**Issue by mmtftr** [hua1995116/google-translate-open-api#14]
I have a project that uses jest for testing and I had problems integrating this package into my tests that was caused by jest's default environment (jsdom). I changed to node for default environment and that fixed my problem. 

I guess my thing is that, this package currently doesn't work on jsdom which might mean that it doesn't support the browser, so you might wanna do browser testing if you want to support it.

**Comment by hua1995116** [comment]
There will be cross-domain issues in the browser, have you encountered the same problem in jsdom?

**Comment by mmtftr** [comment]
Yeah, that was exactly the issue. Is it impossible to get the necessary token within CORS rules?

**Comment by hua1995116** [comment]
You may need a proxy. Like this Issues https://github.com/hua1995116/google-translate-open-api/issues/9

**Comment by mmtftr** [comment]
Can you put a warning when a cors error happens so it is easier to debug
for others?
