### ISSUE TITLE
The Language code for Punjabi is 'pa' not 'ma'

### ISSUE THREAD

**Issue by shessafridi** [hua1995116/google-translate-open-api#23]
Please fix this issue the language code for Punjabi is 'pa' not 'ma'
[https://github.com/hua1995116/google-translate-open-api/blob/master/src/language.ts](url)

**Comment by hua1995116** [comment]
Sorry, it has been fixed in 1.3.6 @shessafridi

**Comment by shessafridi** [comment]
Thanks 😁
