### ISSUE TITLE
Proper handling of multiline texts

### ISSUE THREAD

**Issue by funkyremi** [hua1995116/google-translate-open-api#5]
Hi,

When I translate this text to another language the lines break don't remain:
```
I am a test

I am a test

I am a test
```

Here's the result
```
Soy un examen Soy un examen Soy un examen
```

Could you please try to fix it ?
Thank you!

**Comment by hua1995116** [comment]
Now, if you use a single translation, the format has been fixed. If you want old format, set format to `html`.

**Comment by funkyremi** [comment]
Thanks perfect!
