### ISSUE TITLE
Ability to set an official Google Translate API key

### ISSUE THREAD

**Issue by funkyremi** [hua1995116/google-translate-open-api#6]
Hey,

Could you please add an option to set a custom google translate API key?

Thanks

**Comment by hua1995116** [comment]
I think the official google API is different from this, and this repo goal is to provide a free API to customer.
```
if(hasGoogleKey) {
  // use Google official API
} else {
 // use this API
}
```
you can use above to slove your problem

**Comment by funkyremi** [comment]
Yes I’ll do like that :)
Thanks
