### ISSUE TITLE
频率过高被限制了

### ISSUE THREAD

**Issue by ChenYCL** [hua1995116/google-translate-open-api#8]

**Comment by ChenYCL** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/25706676/78154398-6b113f00-7466-11ea-8662-0b16f9838428.png)

**Comment by hua1995116** [comment]
这个是 cors-anywhere 的限制吧，你可以自己搭建一个跨域的

**Comment by ChenYCL** [comment]
目前是直接跑在浏览器上面，搭建跨域的不是很懂了

**Comment by hua1995116** [comment]
因为由于谷歌翻译api是第三方的，会限制跨域，所以在浏览器是提供了 browers 这个选项来进行跨域的。底层就是通过 cors-anywhere 这个 api 去进行跨域的，因为这个是个公共服务，所以对频率进行了限制，如果你想解除这个限制跨域看 https://github.com/Rob--W/cors-anywhere 他提供了很简单的方式去搭建一套代理服务。

**Comment by ChenYCL** [comment]
嗯  谢谢
我试试部署下
