### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by ztwqy6688o** [hua1995116/google-translate-open-api#9]
Access to XMLHttpRequest at 'https://translate.google.cn/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hua1995116** [comment]
yeah,  in browers you need proxy like https://github.com/Rob--W/cors-anywhere/
